### PR TITLE
provider/vSphere: Support for vSphere via VMC on AWS

### LINKED ISSUE #147: vSphere/VMC Support
Hi,

My team at VMware is working on adding support for vSphere/VMC to the CNCF cross cloud dashboard. We have a few questions that we hope you can answer:

1. Are there concurrent builds? Several designs are currently being reviewed, and they hinge on whether or not we must support multiple, concurrent build environments.
2. How often are builds run? It looks like builds are triggered, but certainly not with every commit? 
3. How is sensitive information handled and stored? It appears we will need to provide you with credentials to access our environment. We would like some more information on how that data is stored.
4. Where, when, and how is the sensitive information available? It appears that it must be available as environment variables to the process that runs `provision.sh`. We need to know if such information is available to `provision.sh` as well as Terraform.
5. Is there any caller-based state between the provision and destroy steps? For example, can `provision.sh` write information to disk during a deploy in order to reuse said information during the destroy step?

Thank you for your time. We've found the existing code and PRs to be useful in getting our work up and running. However, the following would be incredibly useful for us and people in the future:

* A walkthrough on how to add support for a new provider
* A high-level overview of how the environments are provisioned, tests are run, etc.

Thank you again!

### PR DESCRIPTION
**Pull request by akutz**
This PR introduces support for deploying a K8s cluster to vSphere running on [VMware Cloud (VMC) on AWS](https://aws.amazon.com/vmware/). Credentials have been provided to @taylor. The vSphere directory's `README.md` file has instructions on how to use the information to deploy and environment. 

Many thanks to everyone who helped make this PR a reality! I may not be tagging everyone due to saving them from the eventual deluge of e-mail triggered by comments on this PR, but suffice it to say that Hui and I could not have managed this without so many of the fine folks at Vulk :)

cc @figo

Fixes #147

### CODE REVIEW

**Comment by akutz** [comment]
Hi @taylor,

Could you please confirm you've received and are able to decrypt the credentials? Thank you!

**Comment by akutz** [comment]
Hi @taylor,

Is it possible for you to provide an ETA on this PR being reviewed and possibly merged? Thank you!

**Comment by denverwilliams** [comment]
@akutz 
I have started looking over the PR today and will be testing it tomorrow, planning to get it merged within the next 2 days.

**Comment by figo** [comment]
@denverwilliams thank you

**Pull request merged**
