### PR TITLE
ATD-8 Add OCI into cross-cloud

### PR DESCRIPTION
**Pull request by hbscharp**
Add the OCI cloud controller manager, flex volume driver, and volume
provisioner to OCI xcloud clusters. We had to fork the 1.10 templates in
order to work around a CoreOS hostname issue in our downrev image
version and add kubelet back onto the master in order for our
modules to function. The OCI-specific addons are handled with the
addition of a vendor-specific TF module 'addons' that copies and renders the required
files to the container's data mount. The additional steps necessary to
install the addons are then added in a vendor-specific conditional in
the Gitlab CI script.

### CODE REVIEW

**Comment by denverwilliams** [comment]
Conflicts resolved, ready for merge.

**Comment by denverwilliams** [comment]
After some testing we seem to be running into an error with the oci-volume-provisioner, it looks like the 
config file is missing.

```
bash-4.4# kubectl get pods --all-namespaces
NAMESPACE     NAME                                       READY     STATUS             RESTARTS   AGE
kube-system   kube-proxy-oci-master-1.oci.oracle.local   1/1       Running            0          17m
kube-system   kube-proxy-oci-worker-1.oci.oracle.local   1/1       Running            0          16m
kube-system   oci-cloud-controller-manager-gpf64         1/1       Running            0          15m
kube-system   oci-flexvolume-driver-worker-mrcz2         1/1       Running            0          14m
kube-system   oci-volume-provisioner-585c45b794-fz96l    0/1       CrashLoopBackOff   7          14m
```

```
bash-4.4# kubectl logs oci-volume-provisioner-585c45b794-fz96l --namespace=kube-system
W0925 01:44:38.636182       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0925 01:44:38.646529       1 main.go:99] Starting volume provisioner in oracle.com/oci mode
F0925 01:44:38.646593       1 provisioner.go:75] Unable to load volume provisioner configuration file: /etc/oci/config.yaml
```

Steps to reproduce
1. Deploy k8s cluster to oracle cloud using provision.sh 
2. Create rbac roles ```kubectl create -f /cncf/rbac```
3. Create secrets 
``` 
kubectl create secret generic oci-flexvolume-driver \
    -n kube-system \
    --from-file=config.yaml=/cncf/data/addons/create/oci-fvd-secret.yaml 
```
```
kubectl  create secret generic oci-cloud-controller-manager \
     -n kube-system                                           \
     --from-file=cloud-provider.yaml=/cncf/data/addons/create/oci-ccm-secret.yaml 
```
```
kubectl create secret generic oci-volume-provisioner \
    -n kube-system \
    --from-file=config.yaml=/cncf/data/addons/create/oci-vp-secret.yaml
```
4. Lastly deploy the addons and check the logs for the oci-volume-provisioner
``` kubectl create -f /cncf/data/addons/apply/ ```
```kubectl get pods --namespace=kube-system```

**Comment by hbscharp** [comment]
Thanks for the bug report, Denver. I'm sorry you ran into trouble, and that
it took this long for me to respond. This issue will be at the top of our
backlog Monday morning. We'll send a PR when we can.

-Ben

**Comment by hbscharp** [comment]
Denver,

The issue is likely that nothing in your jobs is running the destroy step
as documented in the OCI readme. The allocated compartment had consumed its
quota. There's enough there for 4-5 concurrent iterations, and I think
that's enough. If you run the provision script in the container with the
data volume that contains the terraform plan of that iteration the OCI
resources will be deleted and the quota restored. I have run that manually
and I believe it still works. I have deleted everything in your
compartment. You should have resources to continue again. Please let me
know if we need to contribute the change to run the destroy job at the
correct spot in your pipeline.

Thanks,

-Ben

**Comment by denverwilliams** [comment]
@hbscharp 
Thanks for the Help!

**Comment by hbscharp** [comment]
Thanks, Denver. I've opened ticket ATD-210 internally to track this issue.
I'm not surprised it doesnt work, since we didn't test that before
releasing to you. I was unaware that multi-master was a test case. Seems
strange to me since we're limited to a single node for the ONAP project?

**Comment by denverwilliams** [comment]
@hbscharp thanks for looking into this. In regards to the test case you're right we can only use one node for the onap deployments, however it's only a limitation for the "worker" nodes of the cluster.
Which means we can deploy a multi-master cluster without any issues - also the kubernetes e2e tests don't normally run to well if it's not a multi-master cluster.

Many Thanks,
Denver.

**Comment by hbscharp** [comment]
Denver,

Unfortunately I am unable to reproduce your issue. I do have a change I can
submit to get 3 master nodes up by default. How did you increase the number
of master nodes, and have you changed any versions of Kube packages in your
deployment? I do see some socket errors in etcd in my cluster, but then the
cluster recovers and behaves normally. Does your etcd issue still persist?

Thanks,

-Ben

**Pull request merged**
