### PR TITLE
Add OCI into cross-cloud

### PR DESCRIPTION
**Pull request by doberloh**
Hey there. I believe I am at the stage where I can open a PR and have you all take a look at it. I have tested manually by running the container and letting it do its thing with the provision.sh script. All seems to be working. I followed what appeared to be the standard, one worker and one master in a public zone with a load balancer fronting. I also ran through the kube tests that show in the build from the cncf.ci dashboard and those appear to be working as well. Please let me know if you have any feedback, and I will address ASAP.

### CODE REVIEW

**Comment by doberloh** [comment]
Realized that I will need to add instructions for creating a CoreOS image. That will be coming shortly in another commit.

**Comment by doberloh** [comment]
Anyone had a chance to look at this yet?

**Comment by doberloh** [comment]
Awesome. Please let me know if you need any more work from our end!

**Comment by lixuna** [comment]
Good afternoon, @doberloh. 

Thank you for the PR! I'll send a followup email with a few options for sharing the credentials to the team.

**Comment by doberloh** [comment]
Sent email with credentials. Also got your message about adding the various OCI drivers into the cluster. Will begin work on that as soon as time permits on my end.

**Pull request merged**
